
# menu bar
HEIGHT_MENU_BAR = 20

# borders
TOP_WHITE_BORDER = 3  # color: #ffffff
TOP_GRAY_BORDER = 6  # color: #c0c0c0
LEFT_WHITE_BORDER = 3  # color: #c0c0c0
LEFT_GRAY_BORDER = 6  # color: #c0c0c0
RIGHT_GRAY_BORDER = 5  # color: #c0c0c0
# BOT_GRAY_BORDER = 3  # color: #c0c0c0
BOTTOM_GRAY_BORDER = 5  # color: #c0c0c0
BORDER_TOP_FIELD_BORDER = 6  # color: #c0c0c0

# top frame
OUTER_BORDER_TOP_FRAME = 1  # color: #808080 and #ffffff
INNER_BORDER_TOP_FRAME = 1  # color: #808080 and #ffffff
SPACER_ABOVE_COUNTER = 4
SPACER_LEFT_COUNTER = 5
SPACER_RIGHT_COUNTER = 7
SPACER_BELOW_COUNTER = 4
COUNTER_HEIGHT = 23
COUNTER_WIDTH = 13
BORDER_AROUND_COUNTER = 1
FULL_HEIGHT_TOP_FRAME = OUTER_BORDER_TOP_FRAME*2 + INNER_BORDER_TOP_FRAME*2 + SPACER_ABOVE_COUNTER + SPACER_BELOW_COUNTER + COUNTER_HEIGHT + BORDER_AROUND_COUNTER*2

# smiley
SMILEY_HEIGHT = 24
SMILEY_WIDTH = 24
SMILEY_BORDER = 1

# field frame
BACK_PANEL_HEIGHT = 15
BACK_PANEL_WIDTH = 15
FRONT_PANEL_HEIGHT = 16
FRONT_PANEL_WIDTH = 16
LINE_BETWEEN_FIELDS = 1  # overlaps with panels  # color: #a5a5a5

TOP_FIELD_BORDER_1 = 1
TOP_FIELD_BORDER_2 = 1
TOP_FIELD_BORDER_3 = 1
TOP_FIELD_BORDER = TOP_FIELD_BORDER_1 + TOP_FIELD_BORDER_2 + TOP_FIELD_BORDER_3

LEFT_FIELD_BORDER_1 = 1
LEFT_FIELD_BORDER_2 = 1
LEFT_FIELD_BORDER_3 = 1
LEFT_FIELD_BORDER = LEFT_FIELD_BORDER_1 + LEFT_FIELD_BORDER_2 + LEFT_FIELD_BORDER_3

RIGHT_FIELD_BORDER_1 = 1
RIGHT_FIELD_BORDER_2 = 1
RIGHT_FIELD_BORDER_3 = 1
RIGHT_FIELD_BORDER = RIGHT_FIELD_BORDER_1 + RIGHT_FIELD_BORDER_2 + RIGHT_FIELD_BORDER_3

BOT_FIELD_BORDER_1 = 1
BOT_FIELD_BORDER_2 = 1
BOT_FIELD_BORDER_3 = 1
BOT_FIELD_BORDER = BOT_FIELD_BORDER_1 + BOT_FIELD_BORDER_2 + BOT_FIELD_BORDER_3


# colors
COLOR_WHITE = '#FFFFFF'
COLOR_LIGHT_GRAY = '#c0c0c0'
COLOR_DARK_GRAY = '#808080'
